#!/bin/sh
# ---- base config ----
[user]
	name = Dan Rogers
	email = dan.rogers@bkwld.com
[core]
	excludesfile = ~/.gitignore
	quotepath = false
	whitespace=fix,-indent-with-non-tab,trailing-space,cr-at-eol
	editor = vim
[push]
	default = upstream
[alias]
	st = status
	ci = commit -vam
	co = checkout
	f = fetch
	unstage = reset HEAD
	untrack = rm --cached
	remotes = remote -v
	branches = branch -va --color
	diffs = diff --stat master
	logs = log --stat --color
	sub = submodule add
	subinit = submodule update --init --recursive
	subpull = submodule foreach git pull origin master
	ignore = update-index --assume-unchanged --
	watch = update-index --no-assume-unchanged --
	refresh = update-index --really-refresh
	zip = archive --format zip --output
	diff = difftool
# ---- pretty colors ----
[color]
	ui = true
[color "branch"]
	current = magenta
	remote = cyan
[color "diff"]
	meta = yellow bold
	frag = magenta bold
	old = red reverse
	new = green reverse
	whitespace = white reverse
[color "status"]
	added = green
	changed = cyan
	untracked = blue bold
	branch = magenta
[difftool "Kaleidoscope"]
	cmd = ksdiff --partial-changeset --relative-path \"$MERGED\" -- \"$LOCAL\" \"$REMOTE\"
[diff]
	tool = Kaleidoscope
[difftool]
	prompt = false
[mergetool "Kaleidoscope"]
	cmd = ksdiff --merge --output \"$MERGED\" --base \"$BASE\" -- \"$LOCAL\" --snapshot \"$REMOTE\" --snapshot
[mergetool]
	prompt = false
[merge]
	tool = Kaleidoscope
