" =====================================================================
" MacVim configuration
" " ~/.vim/gvimrc
" =====================================================================

if has("gui_macvim")

  " Colors / font
  colorscheme danro-color
  set guifont=Monaco:h11
  set noantialias

  " GUI Options - remove toolbar, scrollbars
  " add console dialogs, tabs, menubar.
  set guioptions=cemg

  " Esc - quit select mode and go straight to normal mode
  smap <Esc> <C-c>

  " Remove Full Screen key bind
  macmenu Window.Toggle\ Full\ Screen\ Mode key=<nop>

  " Find - remap Command+F to use command mode 
  macmenu Edit.Find.Find\.\.\. key=<nop>
  imap <D-f> <Esc>/
  map <D-f> <Esc>/
  imap <silent> <D-F> <Esc>:promptf<CR>
  map <silent> <D-F> <Esc>:promptf<CR>

  " Find Next - tweak so that it can be used instantly
  macmenu Edit.Find.Find\ Next key=<nop>
  cmap <D-g> <CR>
  map <silent> <D-g> :maca findNext:<CR>
  imap <silent> <D-g> <Esc>:maca findNext:<CR>
  smap <silent> <D-g> <Esc>:maca findNext:<CR>

  " Esc - clear any search highlights
  nnoremap <silent> <Esc> <Esc>:noh<CR>

  " Shift indents with Command+[ or ]
  map <D-]> >gv
  nmap <D-]> >>
  imap <D-]> <Esc><D-]>
  map <D-[> <gv
  nmap <D-[> <<
  imap <D-[> <Esc><D-[>

  " Toggle invisibles with list shortcut
  nmap <silent> <leader>l :set list!<CR>

  " Shift+Space - duplicate selected lines
  map <S-Space> "*_YP

  " Shift+Tab omnifunc completion
  imap <S-Tab> <C-X><C-O>

  " Backspace / delete tweaks:
  " delete whole words with Alt+Backspace
  nmap <A-bs> ciw
  " delete to end of word with Alt+delete
  imap <A-del> <C-[>lce
  nmap <A-del> ce
  " fix backspce and delete behavior
  nmap <bs> a<bs>
  nmap <del> i<del>
  vmap <bs> c
  vmap <del> c
  smap <bs> <C-g>c
  smap <del> <C-g>c

  " Command+d - delete current or visually selected line.
  imap <D-d> <Esc><C-v>Vd
  map <D-d> <C-v>Vd

  " Command+p - replace current line with yank from register.
  macmenu File.Print key=<nop>
  nmap <D-p> V"0p

  " Tweak cursor movement during Alt / Shift
  nmap <A-Right> w
  nmap <A-Left> b
  imap <S-M-Right> <C-[>lve<C-g>
  imap <S-M-Left> <C-[>hvb<C-g>
  nmap <S-M-Right> ve<C-g>
  nmap <S-M-Left> vb<C-g>
  vmap <S-M-Right> e
  vmap <S-M-Left> b
  smap <S-M-Right> <C-O>e
  smap <S-M-Left> <C-O>b

  " Alt + Up/Down for faster vertical cursor movement
  map <A-Down> 7j
  imap <A-Down> <Esc>7ji
  map <A-Up> 7k
  imap <A-Up> <Esc>7ki

  " Command+/ to toggle comments
  map <D-/> <plug>NERDCommenterToggle
  imap <D-/> <Esc><plug>NERDCommenterTogglea

  " CommandT options
  macmenu &File.New\ Tab key=<D-T>
  map <D-t> :CommandT<CR>
  imap <D-t> <Esc>:CommandT<CR>
  let g:CommandTAlwaysShowDotFiles=1
  set wildignore+=-assets,.git,*.gif,*.jpg,*.png,publish,intermediate,node_modules

  " Command+R - Web Dev - reload current web browser 
  imap <silent> <D-r> <Esc>:w<Esc>:silent exe "!~/scripts/web-build.sh"<CR>
  map <silent> <D-r> <Esc>:w<Esc>:silent exe "!~/scripts/web-build.sh"<CR>

  " Command+Return (or Command+R) - ActionScript - handle .as files and map the flash preview
  au Bufread,BufNewFile *.as call s:InitActionScript()
  function s:InitActionScript()
    set filetype=actionscript
    imap <silent> <D-Return> <Esc>:w<CR>:silent exe "!open ~/scripts/flash-preview.jsfl"<CR>
    map <silent> <D-Return> <Esc>:w<CR>:silent exe "!open ~/scripts/flash-preview.jsfl"<CR>
    imap <silent> <D-r> <Esc>:w<CR>:silent exe "!open ~/scripts/flash-preview.jsfl"<CR>
    map <silent> <D-r> <Esc>:w<CR>:silent exe "!open ~/scripts/flash-preview.jsfl"<CR>
  endfunction

  " Command+Z - force command-mode undo 
  " macmenu Edit.Undo key=<nop>
  " macmenu Edit.Redo key=<nop>
  " map <D-z> :undo<CR>
  " map <D-Z> :redo<CR>
  " imap <D-z> <Esc>:undo<CR>
  " imap <D-Z> <Esc>:redo<CR>
  " vmap <D-z> <Esc>:undo<CR>
  " vmap <D-Z> <Esc>:redo<CR>

  " Disable annoying tooltips
  set noballooneval
  
  " Control + Left/Right - move splits around
  " - remember to disable Spaces in OSX
  map <C-Left> <C-w>H<C-w>=
  map <C-Right> <C-w>x<C-w>l<C-w>=

  " Adjust viewports to the same size
  map <Leader>= <C-w>=
  imap <Leader>= <Esc> <C-w>=

  " Return - use insert mode line breaks in normal mode.
  nmap <Return> i<Return>

  " <Leader>] - new file in vertical split
  imap <Leader>] <Esc>:rightb vnew<CR><D-t>
  map <Leader>] <Esc>:rightb vnew<CR><D-t>

  " <Leader>[ - new file in horizontal split
  imap <Leader>[ <Esc>:new<CR><D-t>
  map <Leader>[ <Esc>:new<CR><D-t>

  " Control+Tab - activate surround.vim plugin for current line or selection 
  nmap <C-Tab> ^vg_S
  smap <C-Tab> <C-g>S

  " User commands for frequently edited files
  command -nargs=1 Desk :silent exe "!mvim ~/Desktop/<args>"
  command -nargs=1 Snip :silent exe "!mvim ~/.vim/snippets/<args>.snippets"

" end macvim config
endif

" Include NERDTree config
if filereadable(expand("~/.vim/nerd.vim"))
  source ~/.vim/nerd.vim
endif
