#!/bin/zsh

PATH=$PATH:$HOME/bin # Add user bin to path
PATH=$PATH:$HOME/scripts # Add custom scripts to path
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="danro"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(node npm)

source $ZSH/oh-my-zsh.sh
export EDITOR='sub'

# Custom aliases
alias l='ls -lahGo $*'
alias ll='ls -lhGo $*'
alias profile='sub ~/sites/github/dotfiles/zsh/zshrc'
alias subuser='sub ~/sites/github/dotfiles/sublime'
alias tmproject='cp ~/.dotfiles/.tm_properties ./'
alias shortcuts='sub ~/.dotfiles/zsh/custom/shortcuts.zsh'
alias theme='sub ~/sites/github/dotfiles/zsh/danro.zsh-theme'
alias git-diff-vi='git diff --no-ext-diff -w "$@" | vi -R -'
alias gitignore='cp -v ~/.dotfiles/git/ignore-project .gitignore'
alias node-singlevisor='supervisor -w app.js app.js'
alias asciifonts='cd /usr/local/lib/node_modules/asciimo && node node-all-fonts.js'
